<?php

if ( function_exists( 'acf_add_local_field_group' ) ):

	acf_add_local_field_group( [
		'key'                    => 'group_6717a119cb957',
		'title'                  => 'Buchhaltung',
		'fields'                 => [
			[
				'key'                 => 'field_6717a11a4b205',
				'label'               => 'Dokumente',
				'name'                => 'wps_dashboardpdfs_list',
				'aria-label'          => '',
				'type'                => 'repeater',
				'instructions'        => '',
				'required'            => 0,
				'conditional_logic'   => 0,
				'wrapper'             => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'wpml_cf_preferences' => 1,
				'layout'              => 'block',
				'pagination'          => 0,
				'min'                 => 0,
				'max'                 => 0,
				'collapsed'           => '',
				'button_label'        => 'Dokument hinzufügen',
				'rows_per_page'       => 20,
				'sub_fields'          => [
					[
						'key'                 => 'field_6717a1724b206',
						'label'               => 'Bestellnummer',
						'name'                => 'invoice',
						'aria-label'          => '',
						'type'                => 'text',
						'instructions'        => '',
						'required'            => 0,
						'conditional_logic'   => 0,
						'wrapper'             => [
							'width' => '',
							'class' => '',
							'id'    => '',
						],
						'wpml_cf_preferences' => 2,
						'default_value'       => '',
						'maxlength'           => '',
						'placeholder'         => '',
						'prepend'             => '',
						'append'              => '',
						'parent_repeater'     => 'field_6717a11a4b205',
					],
					[
						'key'                 => 'field_6717a1964b207',
						'label'               => 'Rechnungsnummer',
						'name'                => 'invoiceNumber',
						'aria-label'          => '',
						'type'                => 'text',
						'instructions'        => '',
						'required'            => 0,
						'conditional_logic'   => 0,
						'wrapper'             => [
							'width' => '',
							'class' => '',
							'id'    => '',
						],
						'wpml_cf_preferences' => 2,
						'default_value'       => '',
						'maxlength'           => '',
						'placeholder'         => '',
						'prepend'             => '',
						'append'              => '',
						'parent_repeater'     => 'field_6717a11a4b205',
					],
					[
						'key'                 => 'field_6717a1ab4b208',
						'label'               => 'Lieferscheinnummer',
						'name'                => 'lieferscheinNumber',
						'aria-label'          => '',
						'type'                => 'text',
						'instructions'        => '',
						'required'            => 0,
						'conditional_logic'   => 0,
						'wrapper'             => [
							'width' => '',
							'class' => '',
							'id'    => '',
						],
						'wpml_cf_preferences' => 2,
						'default_value'       => '',
						'maxlength'           => '',
						'placeholder'         => '',
						'prepend'             => '',
						'append'              => '',
						'parent_repeater'     => 'field_6717a11a4b205',
					],
					[
						'key'                 => 'field_6717a1bb4b209',
						'label'               => 'Rechnung als PDF',
						'name'                => 'pdf',
						'aria-label'          => '',
						'type'                => 'file',
						'instructions'        => '',
						'required'            => 0,
						'conditional_logic'   => 0,
						'wrapper'             => [
							'width' => '',
							'class' => '',
							'id'    => '',
						],
						'wpml_cf_preferences' => 1,
						'return_format'       => 'array',
						'library'             => 'all',
						'min_size'            => '',
						'max_size'            => '',
						'mime_types'          => '',
						'parent_repeater'     => 'field_6717a11a4b205',
					],
					[
						'key'                 => 'field_6717a1e94b20a',
						'label'               => 'Lieferschein als PDF',
						'name'                => 'lieferschein',
						'aria-label'          => '',
						'type'                => 'file',
						'instructions'        => '',
						'required'            => 0,
						'conditional_logic'   => 0,
						'wrapper'             => [
							'width' => '',
							'class' => '',
							'id'    => '',
						],
						'wpml_cf_preferences' => 1,
						'return_format'       => 'array',
						'library'             => 'all',
						'min_size'            => '',
						'max_size'            => '',
						'mime_types'          => '',
						'parent_repeater'     => 'field_6717a11a4b205',
					],
				],
			],
		],
		'location'               => [
			[
				[
					'param'    => 'user_role', // 'current_user'
					'operator' => '==',
					'value'    => 'all', // viewing_back
				],
			],
		],
		'menu_order'             => 0,
		'position'               => 'normal',
		'style'                  => 'default',
		'label_placement'        => 'top',
		'instruction_placement'  => 'label',
		'hide_on_screen'         => '',
		'active'                 => TRUE,
		'description'            => '',
		'show_in_rest'           => 0,
		'acfml_field_group_mode' => 'translation',
	] );

endif;