name: Deployment - staging

concurrency: staging

on:
  push:
    branches:
      - staging

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout current Production
        uses: actions/checkout@v3

      - name: Deploy to Production Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          REMOTE_PORT: 22
          SOURCE: "web/"
          TARGET: /staging/